# -*- coding: utf-8 -*-
"""TTMforClinicalPathwayAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OtDJdnMeTMpIKo0NFVgpLmhroLzWYXG
"""

!pip install gensim==4.3.2 numpy pandas scikit-learn matplotlib tqdm tslearn kneed nltk
!pip install "scipy<1.14" gensim
!pip install  "numpy<2.0" "scipy<1.14" "gensim==4.3.2"

import os
import io
import zipfile
import math
import nltk
from collections import Counter, defaultdict

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

from tqdm import tqdm

# --- Patch for gensim + SciPy >=1.14 ---
import scipy.linalg
if not hasattr(scipy.linalg, "triu"):
    scipy.linalg.triu = np.triu

from gensim.corpora import Dictionary
from gensim.models.coherencemodel import CoherenceModel

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import roc_auc_score, accuracy_score, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

# Reproducibility
import random
SEED = 42
rng = np.random.default_rng(SEED)
random.seed(SEED)
np.random.seed(SEED)

plt.rcParams.update({
    'figure.figsize': (8, 5),
    'axes.grid': True
})

# STEP 1: LOAD AND VISUALIZE ORIGINAL DATA

from google.colab import files

print("📤 Upload diabetic_data.csv")
uploaded = files.upload()

# Get filename from uploaded dict
import io
import pandas as pd

filename = list(uploaded.keys())[0]
df_raw = pd.read_csv(io.BytesIO(uploaded[filename]))
print(f"✅ Loaded raw data: {filename}")
print(f"📊 Shape: {df_raw.shape}")
df_raw.head()

# STEP 2: PREPROCESS DATA/ DATA CLEANING

import numpy as np
import os

df = df_raw.copy()

print(f"📊 Original dataset shape: {df.shape}")

# 1. Drop high-missing-value columns
drop_cols = ["weight", "payer_code", "medical_specialty"]
df = df.drop(columns=drop_cols, errors="ignore")

# 2. Drop constant-value columns (no discriminatory info)
constant_cols = [col for col in ["sitagliptin", "examide"] if col in df.columns]
df = df.drop(columns=constant_cols, errors="ignore")

# 3. Impute missing values in race with mode (Caucasian)
if "race" in df.columns:
    df["race"] = df["race"].replace("?", np.nan)
    race_mode = df["race"].mode()[0] if not df["race"].mode().empty else "Caucasian"
    df["race"] = df["race"].fillna(race_mode)

# 4. Convert age category to midpoint numeric
if "age" in df.columns:
    def age_midpoint(age_str):
        if pd.isnull(age_str) or age_str == "?":
            return np.nan
        bounds = age_str.strip("[]").replace(")", "").split("-")
        if len(bounds) == 2:
            low, high = map(int, bounds)
            return (low + high) / 2
        return np.nan
    df["age"] = df["age"].apply(age_midpoint)

# 5. Keep diag_1, diag_2, diag_3 as is (small missing handled later in token step)
for diag_col in ["diag_1", "diag_2", "diag_3"]:
    if diag_col in df.columns:
        df[diag_col] = df[diag_col].replace("?", np.nan)

# Save cleaned dataset
os.makedirs("data", exist_ok=True)
df.to_csv("data/diabetes_preprocessed.csv", index=False)

print(f"✅ Preprocessed dataset saved: data/diabetes_preprocessed.csv")
print(f"📊 New dataset shape: {df.shape}")
df.head()

# STEP 3: DOCUMENTS CREATION

import pandas as pd
import numpy as np
import re
from google.colab import files
uploaded = files.upload()


# === Mappings for categorical IDs ===
admission_type_map = {
    1: "Emergency", 2: "Urgent", 3: "Elective", 4: "Newborn",
    5: "Not Available", 6: "NULL", 7: "Trauma Center", 8: "Not Mapped"
}

discharge_disp_map = {
    1:"Discharged to home", 2:"Discharged/transferred to another short term hospital",
    3:"Discharged/transferred to SNF", 4:"Discharged/transferred to ICF",
    5:"Discharged/transferred to another type of inpatient care institution",
    6:"Discharged/transferred to home with home health service", 7:"Left AMA",
    8:"Discharged/transferred to home under care of Home IV provider",
    9:"Admitted as an inpatient to this hospital", 10:"Neonate discharged to another hospital for neonatal aftercare",
    11:"Expired", 12:"Still patient or expected to return for outpatient services",
    13:"Hospice / home", 14:"Hospice / medical facility",
    15:"Discharged/transferred within this institution to Medicare approved swing bed",
    16:"Discharged/transferred/referred another institution for outpatient services",
    17:"Discharged/transferred/referred to this institution for outpatient services",
    18:"NULL", 19:"Expired at home. Medicaid only, hospice.",
    20:"Expired in a medical facility. Medicaid only, hospice.",
    21:"Expired, place unknown. Medicaid only, hospice.",
    22:"Discharged/transferred to another rehab facility",
    23:"Discharged/transferred to a long term care hospital",
    24:"Discharged/transferred to a Medicaid-only nursing facility",
    25:"Not Mapped", 26:"Unknown/Invalid",
    27:"Discharged/transferred to a federal health care facility",
    28:"Discharged/transferred to a psychiatric hospital",
    29:"Discharged/transferred to a Critical Access Hospital",
    30:"Discharged/transferred to another institution not defined elsewhere"
}

admission_source_map = {
    1:"Physician Referral", 2:"Clinic Referral", 3:"HMO Referral",
    4:"Transfer from hospital", 5:"Transfer from SNF",
    6:"Transfer from other health care facility", 7:"Emergency Room",
    8:"Court/Law Enforcement", 9:"Not Available",
    10:"Transfer from critical access hospital", 11:"Normal Delivery",
    12:"Premature Delivery", 13:"Sick Baby", 14:"Extramural Birth",
    15:"Not Available", 17:"NULL", 18:"Transfer From Another Home Health Agency",
    19:"Readmission to Same Home Health Agency", 20:"Not Mapped",
    21:"Unknown/Invalid", 22:"Transfer from hospital inpt/same fac reslt in sep claim",
    23:"Born inside hospital", 24:"Born outside hospital",
    25:"Transfer from Ambulatory Surgery Center", 26:"Transfer from Hospice"
}

# === Load ICD9 mapping ===
icd9_map = pd.read_csv("icd9_mapping_cleaned.csv")  # has columns CODE and LONG DESCRIPTION
icd9_map["CODE"] = icd9_map["CODE"].astype(str).str.lstrip("0")  # strip leading zeros
icd_dict = dict(zip(icd9_map["CODE"], icd9_map["LONG DESCRIPTION (VALID ICD-9 FY2025)"]))

def map_icd(code):
    if pd.isna(code): return None
    code = str(code).split(".")[0].lstrip("0")
    return icd_dict.get(code, f"ICD_{code}")

# === Token builder ===
def make_content_tokens(row):
    toks = []

    # Demographics
    if pd.notna(row.get("race")):
        toks.append(f"race_{row['race']}")
    if pd.notna(row.get("gender")):
        toks.append(f"gender_{row['gender']}")

    if pd.notna(row.get("age")):
        try:
            age = int(row["age"])
            if age < 10: age_bin = "0-9"
            elif age < 20: age_bin = "10-19"
            elif age < 30: age_bin = "20-29"
            elif age < 40: age_bin = "30-39"
            elif age < 50: age_bin = "40-49"
            elif age < 60: age_bin = "50-59"
            elif age < 70: age_bin = "60-69"
            elif age < 80: age_bin = "70-79"
            else: age_bin = "80+"
            toks.append(f"age_{age_bin}")
        except:
            toks.append(f"age_{row['age']}")

    # Admission/discharge/source mapping
    if pd.notna(row.get("admission_type_id")):
        toks.append(f"admType_{admission_type_map.get(int(row['admission_type_id']), 'Unknown')}")
    if pd.notna(row.get("discharge_disposition_id")):
        toks.append(f"disDisp_{discharge_disp_map.get(int(row['discharge_disposition_id']), 'Unknown')}")
    if pd.notna(row.get("admission_source_id")):
        toks.append(f"admSrc_{admission_source_map.get(int(row['admission_source_id']), 'Unknown')}")

    # Numeric counts (only if >0)
    for col in ["num_lab_procedures","num_procedures","num_medications",
                "number_outpatient","number_emergency","number_inpatient","number_diagnoses"]:
        if col in row and pd.notna(row[col]) and int(row[col]) > 0:
            toks.append(f"{col}_{int(row[col])}")

    # Diagnoses with mapping
    for col in ["diag_1","diag_2","diag_3"]:
        if col in row and pd.notna(row[col]):
            mapped = map_icd(row[col])
            if mapped: toks.append(f"dx_{mapped}")

    # Labs
    for col in ["A1Cresult","max_glu_serum"]:
        if pd.notna(row.get(col)) and str(row[col]).upper() not in {"?", "NONE", "NAN"}:
            toks.append(f"{col}_{row[col]}")

    # Medications
    med_cols = ['metformin','repaglinide','nateglinide','chlorpropamide','glimepiride','acetohexamide',
        'glipizide','glyburide','tolbutamide','pioglitazone','rosiglitazone','acarbose','miglitol',
        'troglitazone','tolazamide','citoglipton','insulin','glyburide-metformin','glipizide-metformin',
        'glimepiride-pioglitazone','metformin-rosiglitazone','metformin-pioglitazone']
    for col in med_cols:
        if pd.notna(row.get(col)) and row[col] not in ["No","?","Nan","nan","NONE"]:
            toks.append(f"{col}_{row[col]}")

    return toks if toks else ["_empty_"]

# === Temporal binning: index-based 10-day bins (no encounter_date available) ===
def build_10day_bins(df, n_bins=365):
    """
    Create ~365 bins across dataset (index-based).
    Each bin is like a synthetic '10-day' time window.
    """
    bin_size = int(np.ceil(len(df) / n_bins))   # rows per bin
    bins = (df.reset_index().index // bin_size).astype(int)
    return bins, int(bins.max() + 1)


# === Apply to dataframe ===
df = pd.read_csv("data/diabetes_preprocessed.csv")   # <-- your dataset

t_globals, B = build_10day_bins(df, n_bins=365)
df["t_global"] = t_globals

docs, doc_ids, patients, time_bins = [], [], [], []
extra_cols = {"time_in_hospital": [], "change": [], "diabetesMed": [], "readmitted": []}

for _, row in df.iterrows():
    toks = make_content_tokens(row)
    docs.append(" ".join(toks))   # join as single string
    doc_ids.append(row["encounter_id"])
    patients.append(row["patient_nbr"])
    time_bins.append(int(row["t_global"]))
    # preserve extra columns
    extra_cols["time_in_hospital"].append(row["time_in_hospital"])
    extra_cols["change"].append(row["change"])
    extra_cols["diabetesMed"].append(row["diabetesMed"])
    extra_cols["readmitted"].append(row["readmitted"])

# Save final CSV
out_df = pd.DataFrame({
    "encounter_id": doc_ids,
    "patient_nbr": patients,
    "t_global": time_bins,
    "time_in_hospital": extra_cols["time_in_hospital"],
    "change": extra_cols["change"],
    "diabetesMed": extra_cols["diabetesMed"],
    "readmitted": extra_cols["readmitted"],
    "document": docs
})
out_df.to_csv("diabetes_docs_merged_single_view.csv", index=False)

print(f"✅ Built {len(docs)} documents across {B} bins")
print("📌 Sample document:", docs[0])

# STEP 4: BUILD DICTIONARY
import pandas as pd
import nltk
import re
import csv
from nltk.corpus import stopwords
from gensim.corpora import Dictionary

# 1. Load your specific columns correctly
try:
    df = pd.read_csv(
        'male_documents.csv',
        usecols=['encounter_id', 'patient_nbr', 't_global', 'document'],
        quotechar='"',
        doublequote=True,
        on_bad_lines='skip',
        engine='python'
    )

    df['t_global'] = pd.to_numeric(df['t_global'], errors='coerce')
    df = df.dropna(subset=['t_global'])
    df['t_global'] = df['t_global'].astype(int)

    print(f"✅ Successfully loaded {len(df)} rows.")
except Exception as e:
    print(f"⚠️ Error during load: {e}")

docs_raw = df['document'].astype(str).tolist()
time_bins = df['t_global'].tolist()

# 2. Setup stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Define prefixes to remove
unwanted_prefixes = ('race', 'admissiontype', 'agegroup')

# 3. Pre-clean: Split by comma, remove punctuation/numbers, remove stopwords & prefixes
docs = []
for d in docs_raw:
    raw_tokens = d.lower().split(',')

    cleaned_tokens = []
    for t in raw_tokens:
        # Keep only letters and underscores
        clean_word = re.sub(r'[^a-zA-Z_]', '', t)

        # Check if word:
        # 1. Is not empty
        # 2. Is not in stop_words
        # 3. Does NOT start with unwanted prefixes
        if clean_word and clean_word not in stop_words:
            if not clean_word.startswith(unwanted_prefixes):
                cleaned_tokens.append(clean_word)
    docs.append(cleaned_tokens)

# 4. Build dictionary
dictionary = Dictionary(docs)
# Tightening no_above to 0.2 forces the model to ignore words common to >20% of docs
dictionary.filter_extremes(no_below=5, no_above=0.2)
dictionary.compactify()

# 5. Convert all docs to BOW
bow_all = [dictionary.doc2bow(d) for d in docs]

# 6. Group corpus by t_global
n_bins = int(df['t_global'].max() + 1)
corpus_by_bin = [[] for _ in range(n_bins)]
doc_index_by_bin = [[] for _ in range(n_bins)]

for i, (z, bow) in enumerate(zip(time_bins, bow_all)):
    corpus_by_bin[z].append(bow)
    doc_index_by_bin[z].append(i)

print("Vocab size:", len(dictionary))
print("Docs per bin:", [len(c) for c in corpus_by_bin])

print(df.columns)

# STEP 5: TTM CLASS
from tqdm import tqdm
class TemporalLDA:
    def __init__(self, dictionary, corpus_by_bin, K=20, alpha=0.1, beta=0.01,
                 delta=0.4, iters=150, seed=42):
        self.dictionary = dictionary
        self.id2word = dictionary.id2token
        self.V = len(dictionary)
        self.corpus_by_bin = corpus_by_bin
        self.B = len(corpus_by_bin)   # number of time bins
        self.K = K
        self.alpha = np.full(K, alpha) if np.isscalar(alpha) else np.array(alpha)
        self.beta_prior = np.full(self.V, beta) if np.isscalar(beta) else np.array(beta)
        self.delta = delta
        self.iters = iters
        self.seed = seed
        self.random = np.random.default_rng(seed)

        # Counts
        self.topic_word_counts = [np.zeros((K, self.V), dtype=np.int64) for _ in range(self.B)]
        self.topic_counts = [np.zeros(K, dtype=np.int64) for _ in range(self.B)]
        self.doc_topic_counts = []
        self.assignments = []
        self.docs_wordids = []
        self.bin_doc_index = []

        # Learned parameters
        self.phi = None   # topic-word distributions per bin
        self.theta = None # doc-topic distributions per bin
        self.final_phi = None  # final learned topic-word distribution

    def _initialize_bin(self, bin_idx, corpus_bin):
        """Randomly assign topics for a given bin and initialize counts."""
        docs_wids = []
        for bow in corpus_bin:
            wids = []
            for wid, cnt in bow:
                wids.extend([wid] * cnt)
            docs_wids.append(np.array(wids, dtype=np.int32))
        self.docs_wordids.append(docs_wids)
        self.bin_doc_index.append([])

        D = len(docs_wids)
        dtc = [np.zeros(self.K, dtype=np.int32) for _ in range(D)]
        zlist = []
        for d, wids in enumerate(docs_wids):
            z = np.empty_like(wids)
            for n, wid in enumerate(wids):
                k = self.random.integers(0, self.K)
                z[n] = k
                self.topic_word_counts[bin_idx][k, wid] += 1
                self.topic_counts[bin_idx][k] += 1
                dtc[d][k] += 1
            zlist.append(z)
        self.doc_topic_counts.append(dtc)
        self.assignments.append(zlist)

    def fit(self, doc_index_by_bin):
        """Run collapsed Gibbs sampling with temporal smoothing."""
        self.bin_doc_index = doc_index_by_bin
        for b in range(self.B):
            self._initialize_bin(b, self.corpus_by_bin[b])

        for it in tqdm(range(self.iters), desc="Training TTM"):
            for b in range(self.B):
                prev_phi = None
                if b > 0:
                    tp = self.topic_word_counts[b-1] + 1e-9
                    tp = tp / tp.sum(axis=1, keepdims=True)
                    prev_phi = tp

                for d, wids in enumerate(self.docs_wordids[b]):
                    z = self.assignments[b][d]
                    dtc = self.doc_topic_counts[b][d]
                    for n, wid in enumerate(wids):
                        k = z[n]
                        # remove
                        self.topic_word_counts[b][k, wid] -= 1
                        self.topic_counts[b][k] -= 1
                        dtc[k] -= 1

                        # conditional
                        left = (dtc + self.alpha)
                        if prev_phi is None:
                            right_num = self.topic_word_counts[b][:, wid] + self.beta_prior[wid]
                            right_den = self.topic_counts[b] + self.beta_prior.sum()
                        else:
                            right_num = self.topic_word_counts[b][:, wid] + self.beta_prior[wid] + self.delta * prev_phi[:, wid]
                            right_den = self.topic_counts[b] + self.beta_prior.sum() + self.delta
                        p = left * (right_num / np.maximum(right_den, 1e-12))
                        k_new = self.random.choice(self.K, p=p / np.sum(p))
                        z[n] = k_new

                        # add
                        self.topic_word_counts[b][k_new, wid] += 1
                        self.topic_counts[b][k_new] += 1
                        dtc[k_new] += 1

        # compute phi and theta
        self.phi = []
        self.theta = []
        for b in range(self.B):
            prev_phi = None
            if b > 0:
                tp = self.topic_word_counts[b-1] + 1e-9
                tp = tp / tp.sum(axis=1, keepdims=True)
                prev_phi = tp

            if prev_phi is None:
                pw = self.topic_word_counts[b] + self.beta_prior
            else:
                pw = self.topic_word_counts[b] + self.beta_prior + self.delta * prev_phi
            pw = pw / pw.sum(axis=1, keepdims=True)
            self.phi.append(pw)

            D = len(self.docs_wordids[b])
            thetab = np.zeros((D, self.K), dtype=np.float64)
            for d in range(D):
                counts = self.doc_topic_counts[b][d] + self.alpha
                thetab[d] = counts / counts.sum()
            self.theta.append(thetab)

        # save final phi (last time bin)
        self.final_phi = self.phi[-1]
        return self

    def get_top_words(self, topic_id=None, topn=10, bin_idx=None):
      id2word = self.dictionary.id2token

      # Select which phi (topic-word distribution) to use
      if bin_idx is not None:
          if bin_idx < 0 or bin_idx >= self.B:
              return {} if topic_id is None else []
          beta = self.phi[bin_idx]
      else:
          beta = np.mean(self.phi, axis=0) if isinstance(self.phi, list) else self.phi

      # For single topic request
      if topic_id is not None:
          if topic_id < 0 or topic_id >= self.K:
            return []

          top_indices = np.argsort(beta[topic_id])[::-1][:topn]
          return [(id2word[idx], float(beta[topic_id][idx]))
                for idx in top_indices if idx in id2word]

      # For all topics
      all_topics = {}
      for tid in range(self.K):
          top_indices = np.argsort(beta[tid])[::-1][:topn]
          all_topics[tid] = [(id2word[idx], float(beta[tid][idx]))
                          for idx in top_indices if idx in id2word]
      return all_topics


    def doc_topic_matrix(self, doc_index_by_bin):
        """Return global doc-topic matrix aligned with original doc indices."""
        D = sum(len(x) for x in doc_index_by_bin)
        M = np.zeros((D, self.K), dtype=float)
        for b in range(self.B):
            for local_idx, global_idx in enumerate(doc_index_by_bin[b]):
                M[global_idx] = self.theta[b][local_idx]
        return M

# STEP 6: METRICS AND UTILITIES

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from gensim.models import CoherenceModel
from tslearn.metrics import dtw as dtw_distance  # For temporal DTW similarity

# 1️⃣ Perplexity
def compute_perplexity(ttm, dictionary, texts):
    total_words = 0
    log_likelihood = 0.0

    # Average topic-word distributions over time bins
    phi_avg = np.mean(np.array(ttm.phi), axis=0)  # shape: (K, vocab_size)
    num_bins = len(ttm.theta)

    for d_idx, doc in enumerate(texts):
        bow = dictionary.doc2bow(doc)
        if not bow:
            continue

        total_words += sum(cnt for _, cnt in bow)

        # Collect this doc's theta from each bin where it exists
        theta_list = [
            ttm.theta[b][d_idx]
            for b in range(num_bins)
            if d_idx < len(ttm.theta[b])
        ]
        if not theta_list:
            continue

        # Average theta across bins for this document
        theta_doc = np.mean(theta_list, axis=0)  # shape: (K,)

        # Log likelihood for each word in the document
        for word_id, cnt in bow:
            pw = np.dot(theta_doc, phi_avg[:, word_id])
            if pw > 0:
                log_likelihood += cnt * np.log(pw)

    if total_words == 0:
        return 0.0

    # Gensim-style perplexity
    perplexity = np.exp(-log_likelihood / total_words)
    return perplexity


# 2️⃣ Coherence (normalized)
def compute_coherence(model, docs, dictionary, topn=20):
    top_words = []
    for k in range(model.K):
        # get sorted indices and flatten them to 1D ints
        top_indices = np.argsort(model.phi[k])[-topn:].flatten()
        words = [dictionary[int(i)] for i in top_indices]
        top_words.append(words)

    cm = CoherenceModel(
        topics=top_words,
        texts=docs,
        dictionary=dictionary,
        coherence='c_v'
    )
    return cm.get_coherence()


# 3️⃣ NKQM@N (embedding-based)
def compute_nkqm_for_ttm(model, embed_model, topn=20, Nlist=[5, 10, 15]):
    topic_topwords = {
        tid: [w for w, _ in model.get_top_words(tid, topn=topn)]
        for tid in range(model.K)
    }
    all_words = list({w for words in topic_topwords.values() for w in words})
    if not all_words:
        return {N: 0.0 for N in Nlist}

    # Embeddings
    word_embeddings = embed_model.encode(all_words, convert_to_numpy=True, show_progress_bar=False)
    word_to_emb = dict(zip(all_words, word_embeddings))

    # Relevance scores
    relevance_scores = {}
    for tid, words in topic_topwords.items():
        emb_list = [word_to_emb[w] for w in words if w in word_to_emb]
        if not emb_list:
            continue
        centroid = np.mean(emb_list, axis=0)
        for w in words:
            if w in word_to_emb:
                sim = cosine_similarity([word_to_emb[w]], [centroid])[0][0]
                relevance_scores[w] = max(sim, 0)

    def compute_normalized_nkqm(topic_topwords, relevance_scores, N):
        scores = []
        max_possible = sum(1 / np.log2(rank + 1) for rank in range(1, N + 1))
        for tid, words in topic_topwords.items():
            s = 0.0
            for rank, word in enumerate(words[:N], start=1):
                rel = relevance_scores.get(word, 0.0)
                s += rel / np.log2(rank + 1)
            scores.append(s / max_possible)
        return float(np.mean(scores)) if scores else 0.0

    return {N: compute_normalized_nkqm(topic_topwords, relevance_scores, N) for N in Nlist}


# 4️⃣ Cosine Similarity of Topic–Word Distributions across time bins (normalized)
def cosine_smoothness(ttm):
    smooth_vals = []
    for topic_id in range(ttm.K):
        n_bins = len(ttm.phi[topic_id])               # actual number of bins for this topic
        for b in range(1, n_bins):
            sim = cosine_similarity(
                [ttm.phi[topic_id][b - 1]],
                [ttm.phi[topic_id][b]]
            )[0][0]
            smooth_vals.append((sim + 1) / 2)        # normalize [-1,1] → [0,1]
    return np.mean(smooth_vals) if smooth_vals else 0.0


# 5️⃣ Jaccard similarity of top-N words across time bins (normalized)
def jaccard_stability(ttm, N=10):
    scores = []
    for topic_id in range(ttm.K):
        for b in range(1, ttm.B):
            top_prev = {w for w, _ in ttm.get_top_words(topic_id, bin_idx=b - 1, topn=N)}
            top_curr = {w for w, _ in ttm.get_top_words(topic_id, bin_idx=b, topn=N)}
            union_size = len(top_prev | top_curr)
            inter_size = len(top_prev & top_curr)
            score = inter_size / union_size if union_size > 0 else 0
            scores.append(score)
    return np.mean(scores) if scores else 0.0


# 6️⃣ DTW-based topic distribution similarity across time bins
def dtw_topic_similarity(ttm):
    """Compute average DTW distance across consecutive bins for each topic."""
    dtw_vals = []
    for topic_id in range(ttm.K):
        n_bins = len(ttm.phi[topic_id])   # actual number of available bins for this topic
        for b in range(1, n_bins):
            series_prev = ttm.phi[topic_id][b - 1]
            series_curr = ttm.phi[topic_id][b]
            dtw_dist = dtw_distance(series_prev, series_curr)
            dtw_vals.append(1 / (1 + dtw_dist))  # normalize to [0,1]
    return np.mean(dtw_vals) if dtw_vals else 0.0

# STEP 7: K OPTIMIZATION, Finding best metric scores
import matplotlib.pyplot as plt
import pandas as pd
import gc
from sentence_transformers import SentenceTransformer
from kneed import KneeLocator

embed_model = SentenceTransformer('all-MiniLM-L6-v2')

K_values = [3,4,5,6,7,8,9,10]  # adjust as needed
alpha0, beta0, delta0 = 0.3, 0.005, 0.2
iters0 = 5  # increase for better stability

results_k = []

for K in K_values:
    print(f"Training TTM with K={K} ...")
    model = TemporalLDA(dictionary, corpus_by_bin, K=K, alpha=alpha0, beta=beta0, delta=delta0, iters=iters0, seed=SEED)
    model.fit(doc_index_by_bin)

    perp = compute_perplexity(model, dictionary, docs)
    coh = compute_coherence(model, docs, dictionary, topn=20)

    # NKQM@5,10,15
    top_words_dict = {tid: [w for w, _ in words] for tid, words in model.get_top_words(topn=20).items()}
    nkqm_scores = compute_nkqm_for_ttm(model, embed_model, Nlist=[5,10,15])

    results_k.append({
        'K': K,
        'Perplexity': perp,
        'Coherence': coh,
        'NKQM@5': nkqm_scores[5],
        'NKQM@10': nkqm_scores[10],
        'NKQM@15': nkqm_scores[15]
    })

    print(f"{'Coherence (c_v)':<20}  {coh:.5f}")
    print(f"{'Perplexity':<20}  {perp:.4f}")
    print(f"{'NKQM@5':<20}  {nkqm_scores[5]:.5f}")
    print(f"{'NKQM@10':<20}  {nkqm_scores[10]:.5f}")
    print(f"{'NKQM@15':<20}  {nkqm_scores[15]:.5f}")
    print(f"{'─'*40}")

    del model
    gc.collect()

resK = pd.DataFrame(results_k)
display(resK)

# ---------- Plot + Knee Function ----------
def plot_with_knee_single(x, y, ylabel, title, filename, curve, direction):
    plt.figure(figsize=(7,5))
    plt.rcParams.update({'font.family':'serif', 'font.size':12})  # generic serif font

    plt.plot(x, y, marker='o', linestyle='-', color='tab:blue', label=ylabel)

    plt.xlabel("Number of Topics (K)")
    plt.ylabel(ylabel)
    plt.title(title)
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.legend(loc='best')
    plt.tight_layout()
    plt.savefig(filename, format='pdf')
    plt.show()

    # Knee detection
    try:
        kneedle = KneeLocator(x, y, curve=curve, direction=direction)
        return kneedle.knee
    except:
        return None

# ---------- Prepare data ----------
metrics_config = {
    'Perplexity': ("Perplexity vs K", "perplexity_vs_K.pdf", "convex", "decreasing"),
    'Coherence': ("Coherence vs K", "coherence_vs_K.pdf", "concave", "increasing"),
    'NKQM@5': ("NKQM@5 vs K", "nkqm5_vs_K.pdf", "concave", "increasing"),
    'NKQM@10': ("NKQM@10 vs K", "nkqm10_vs_K.pdf", "concave", "increasing"),
    'NKQM@15': ("NKQM@15 vs K", "nkqm15_vs_K.pdf", "concave", "increasing"),
}

knees = {}
for metric, (title, filename, curve, direction) in metrics_config.items():
    knees[metric] = plot_with_knee_single(
        K_values,
        resK[metric],
        ylabel=metric,
        title=title,
        filename=filename,
        curve=curve,
        direction=direction
    )

print("\n📌 Suggested Knees/Elbows for K selection:")
for metric, knee in knees.items():
    print(f"  • {metric}: {knee}")

# STEP 8: GRID SEARCH OPTIMIZATION for k

import matplotlib.pyplot as plt
import pandas as pd
import time
import gc
import os

k_grid=[10]
alpha_grid = [0.1, 0.3, 0.5]
beta_grid  = [0.005, 0.01, 0.1]
delta_grid = [0.1, 0.2, 0.3]
iters_grid = 5  # adjust as needed

total_combos = len(alpha_grid) * len(beta_grid) * len(delta_grid)*len(k_grid)
print(f"Total parameter combos: {total_combos}\n")

# Header
print(f"{'K':<3} {'alpha':<6} {'beta':<6} {'delta':<6} {'coh':<8} {'nkqm@5':<8} {'nkqm@10':<8} {'nkqm@15':<8} {'time(s)':<7}")

grid_results = []
for topic in k_grid:
  for a in alpha_grid:
      for b in beta_grid:
          for dlt in delta_grid:
              start_time = time.time()

              model = TemporalLDA(dictionary, corpus_by_bin, K=topic, alpha=a, beta=b, delta=dlt, iters=iters_grid, seed=SEED)
              model.fit(doc_index_by_bin)

              coh = compute_coherence(model, docs, dictionary, topn=20)

              # embedding-based NKQM for multiple N
              top_words_dict = {tid: [w for w, _ in model.get_top_words(tid, topn=20)] for tid in range(model.K)}
              nkqm_scores = compute_nkqm_for_ttm(model, embed_model, Nlist=[5,10,15])

              elapsed = round(time.time() - start_time, 2)

              # Record results
              row = {
                  'K': topic,
                  'alpha': a,
                  'beta': b,
                  'delta': dlt,
                  'coh': round(coh,5),
                  'nkqm@5': round(nkqm_scores.get(5,0),5),
                  'nkqm@10': round(nkqm_scores.get(10,0),5),
                  'nkqm@15': round(nkqm_scores.get(15,0),5),
                  'time(s)': elapsed
              }
              grid_results.append(row)

              # Print current row
              print(f"{row['K']:<3} {row['alpha']:<6} {row['beta']:<6} {row['delta']:<6} {row['coh']:<8} "
                    f"{row['nkqm@5']:<8} {row['nkqm@10']:<8} {row['nkqm@15']:<8} {row['time(s)']:<7}")

              del model
              gc.collect()

# ---------- Convert to DataFrame ----------
results_df = pd.DataFrame(grid_results)

# Sort by coherence then NKQM@10 descending
results_df = results_df.sort_values(by=['coh','nkqm@10'], ascending=False).reset_index(drop=True)

# Optional: save CSV
OUT_DIR = "./"
results_df.to_csv(os.path.join(OUT_DIR,"ttm_param_grid_results.csv"), index=False)

print("\nGrid search complete. Top 10 results:")
display(results_df.head(10))

# STEP 9: SELECT BEST PARAMETERS for k = 10

# Make a copy of the grid results
res = pd.DataFrame(grid_results).copy()

# Weights for combining metrics (adjust as needed)
w_coh = 0.6
w_nkqm10 = 0.4
# Optional: include nkqm15 if available, adjust weights accordingly

# Compute combined score
res['combined_score'] = (w_coh * res['coh'] +
                         w_nkqm10 * res.get('nkqm@10', 0))

# Sort by combined score descending and select the top row
best_params = res.sort_values('combined_score', ascending=False).iloc[0]

print("📌 Selected Best Parameters:")
print(f"  K     : {best_params['K']}")
print(f"  alpha : {best_params['alpha']}")
print(f"  beta  : {best_params['beta']}")
print(f"  delta : {best_params['delta']}")
print(f"  Combined Score : {best_params['combined_score']:.5f}")

# STEP 10: FINAL TRAINING

import os
import pickle

# Parameters
final_iters = 50 # number of iterations for final training
#bestK = int(best_params['K'])
#best_alpha = float(best_params['alpha'])
#best_beta = float(best_params['beta'])
#best_delta = float(best_params['delta'])

bestK=10
best_alpha=0.3
best_beta=0.01
best_delta=0.3

# Path to save model

model_path = os.path.join("final_ttm_model.pkl")

print(f"🚀 Training FINAL TTM with K={bestK}, alpha={best_alpha}, beta={best_beta}, delta={best_delta}, iters={final_iters}")

# Train fresh final model
ttm = TemporalLDA(dictionary, corpus_by_bin, K=bestK, alpha=best_alpha,
                  beta=best_beta, delta=best_delta, iters=final_iters, seed=SEED)
ttm.fit(doc_index_by_bin)

# Save the trained model
with open(model_path, "wb") as f:
    pickle.dump(ttm, f)

print(f"✅ Final TTM trained and saved at {model_path}")

# STEP 11: FINAL METRICS

import pandas as pd
from sentence_transformers import SentenceTransformer

embed_model = SentenceTransformer('all-MiniLM-L6-v2')

# 1️⃣ Perplexity
final_perp = compute_perplexity(ttm, dictionary, docs)

# 2️⃣ Coherence
final_coh = compute_coherence(ttm, docs, dictionary, topn=20)

# 3️⃣ NKQM@N using safe get_top_words
all_topics_safe = ttm.get_top_words(topn=20)  # returns dict
top_words_dict = {}
for tid in range(ttm.K):
    words_scores = all_topics_safe.get(tid, [])
    top_words = [w for w, _ in words_scores] if words_scores else []
    top_words_dict[tid] = top_words

# Compute NKQM@N (requires embed_model)
final_nkqm_scores = compute_nkqm_for_ttm(ttm, embed_model, Nlist=[5,10,15])
final_nkqm5 = final_nkqm_scores.get(5, None)
final_nkqm10 = final_nkqm_scores.get(10, None)
final_nkqm15 = final_nkqm_scores.get(15, None)

# 4️⃣ Cosine & Jaccard (optional; can be uncommented if needed)
final_cos = cosine_smoothness(ttm)
final_jac = jaccard_stability(ttm, N=15)

# 5️⃣ DTW-based topic similarity
final_dtw = dtw_topic_similarity(ttm)

# 6️⃣ Summary dataframe
summary = pd.DataFrame([{
    'K': bestK,
    'alpha': best_alpha,
    'beta': best_beta,
    'delta': best_delta,
    'perplexity': final_perp,
    'coherence_c_v': final_coh,
    'NKQM@5': final_nkqm5,
    'NKQM@10': final_nkqm10,
    'NKQM@15': final_nkqm15,
    'cosine': final_cos,
    'jaccard': final_jac,
    'DTW_similarity': final_dtw
}])

display(summary)

# STEP 12: TOP WORDS FROM EACH TOPIC
TOPN = 15
top_words = ttm.get_top_words(topn=TOPN)
for k in range(ttm.K):
    print(f"\nTopic {k}:")
    for w, p in top_words[k]:
        print(f"  {w:25s}  {p:.4f}")

import pandas as pd

all_data = []
TOPN = len(ttm.dictionary)
all_words = ttm.get_top_words(topn=TOPN)

for k in range(ttm.K):
    for w, p in all_words[k]:
        all_data.append({'Topic': k, 'Word': w, 'Probability': p})

# Save to CSV
df_topics = pd.DataFrame(all_data)
df_topics.to_csv('male_ttm_all_topic_words.csv', index=False)
print("✅ Saved all topic words to 'male_ttm_all_topic_words.csv'")

# STEP 13: TOPIC TRENDS OVER TIME BINS

import matplotlib.pyplot as plt
import numpy as np
import os

OUT_DIR = "plots"  # directory to save PDFs
os.makedirs(OUT_DIR, exist_ok=True)

# Average topic probability per bin
avg_theta_by_bin = []
for b in range(ttm.B):
    if len(ttm.theta[b]) == 0:
        avg_theta_by_bin.append(np.zeros(ttm.K))
    else:
        avg_theta_by_bin.append(np.mean(ttm.theta[b], axis=0))
avg_theta_by_bin = np.array(avg_theta_by_bin)  # shape: (B, K)

# X-axis tick positions (every 50 bins)
x = np.arange(ttm.B)
xticks = x[::50]

# --- Combined topic trends ---
plt.figure(figsize=(12,6))
for k in range(ttm.K):
    plt.plot(x, avg_theta_by_bin[:, k], marker='.', markersize=6, linestyle='-', label=f'Topic {k}')
plt.title('All Topics: Mean Probability over Time Bins', fontsize=14, fontweight='bold')
plt.xlabel('Time bin', fontsize=12)
plt.ylabel('Mean topic probability', fontsize=12)
plt.xticks(xticks)  # show every 50th bin
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc='center left', bbox_to_anchor=(1,0.5))
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "all_topics_mean_probability.pdf"))
plt.show()

# --- Individual topic trends ---
for k in range(ttm.K):
    plt.figure(figsize=(10,5))
    plt.plot(x, avg_theta_by_bin[:, k], marker='.', markersize=6, linestyle='-')
    plt.title(f'Topic {k} Mean Probability over Time Bins', fontsize=14, fontweight='bold')
    plt.xlabel('Time bin', fontsize=12)
    plt.ylabel('Mean topic probability', fontsize=12)
    plt.xticks(xticks)
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.tight_layout()
    plt.savefig(os.path.join(OUT_DIR, f"topic_{k}_mean_probability.pdf"))
    plt.show()

# --- Topic frequency per bin: dominant topic counts ---
dom_counts = np.zeros((ttm.B, ttm.K), dtype=int)
for b in range(ttm.B):
    for d in range(len(ttm.theta[b])):
        k_star = int(np.argmax(ttm.theta[b][d]))
        dom_counts[b, k_star] += 1

# Bar chart per topic: frequency across bins
for k in range(ttm.K):
    plt.figure(figsize=(12,5))
    plt.bar(x, dom_counts[:, k], color='skyblue')
    plt.title(f'Topic {k} Document Frequency per Time Bin', fontsize=14, fontweight='bold')
    plt.xlabel('Time bin', fontsize=12)
    plt.ylabel('Doc count (dominant topic)', fontsize=12)
    plt.xticks(xticks)
    plt.grid(True, linestyle='--', alpha=0.6, axis='y')
    plt.tight_layout()
    plt.savefig(os.path.join(OUT_DIR, f"topic_{k}_doc_frequency.pdf"))
    plt.show()

# STEP 14: DOWNLOAD ALL FILES IN ZIP FOLDER

import os
import zipfile
from google.colab import files

# Name of the ZIP file
zip_filename = "all_notebook_files.zip"

# Create a zip file
with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files_list in os.walk('.'):
        for file in files_list:
            # Skip hidden files and the ZIP itself
            if file.startswith('.') or file == zip_filename:
                continue
            file_path = os.path.join(root, file)
            zipf.write(file_path, arcname=file)  # Keep original file name in ZIP

print(f"All files zipped into '{zip_filename}'.")

# Trigger download in Colab
files.download(zip_filename)